# Generated by Django 6.0.6 on 2026-08-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        ('vocabulary_app', '0002_vocabularyword_created_at_vocabularyword_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='words',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='word',
        ),
        migrations.AddField(
            model_name='quiz',
            name='concepts',
            field=models.ManyToManyField(related_name='quizzes', to='vocabulary_app.vocabularyconcept'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='native_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='native_quizzes', to='vocabulary_app.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='target_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='target_quizzes', to='vocabulary_app.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vocabulary_app.vocabularyconcept'),
            preserve_default=False,
        ),
    ]
