# Generated by Django 6.0.6 on 2026-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='direction',
            field=models.CharField(choices=[('FORWARD', 'Source → Target'), ('REVERSE', 'Target → Source')], default='FORWARD', max_length=10),
        ),
    ]
