# Generated by Django 6.0.6 on 2026-07-30 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['language_name'],
            },
        ),
        migrations.CreateModel(
            name='UserLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_languages', models.ManyToManyField(blank=True, related_name='learners', to='vocabulary_app.language')),
                ('native_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='native_speakers', to='vocabulary_app.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='STANDARD', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary_categories', to='vocabulary_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_concepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('tip', models.CharField(blank=True, max_length=255)),
                ('sentence', models.TextField(blank=True)),
                ('rank', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='vocabulary_app.vocabularycategory')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vocabulary_app.vocabularyconcept')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='vocabulary_app.language')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='vocabularycategory',
            constraint=models.UniqueConstraint(fields=('user', 'target_language', 'category_name'), name='unique_category_per_language'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyword',
            constraint=models.UniqueConstraint(fields=('concept', 'language'), name='unique_translation_per_language'),
        ),
    ]
