# Generated by Django 6.0.6 on 2026-07-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularyword',
            name='language',
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='target_language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='vocabulary_app.language'),
            preserve_default=False,
        ),
    ]
