# Generated by Django 6.0.6 on 2026-06-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabularyword',
            options={'ordering': ['id']},
        ),
    ]
