# Generated by Django 6.0.6 on 2026-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0002_vocabularyword_created_at_vocabularyword_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
