# Generated by Django 6.0.6 on 2026-07-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0003_language_vocabularycategory_target_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularycategory',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary_categories', to='vocabulary_app.language'),
        ),
    ]
