# Generated by Django 6.0.6 on 2026-07-13 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0004_alter_vocabularycategory_target_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabularycategory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='vocabularycategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(default='Without', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='vocabularycategory',
            constraint=models.UniqueConstraint(fields=('user', 'target_language', 'name'), name='unique_category_per_language'),
        ),
    ]
