# Generated by Django 6.0.6 on 2026-09-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('quiz_app', '0002_remove_quiz_words_remove_quizanswer_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_flipcard_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz_app.quiz'),
        ),
    ]
